//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crew
    {
        public int NumberHuman { get; set; }
        public string lastname { get; set; }
        public string Name { get; set; }
        public string Patronomyc { get; set; }
        public string DateBirthday { get; set; }
    }
}
