//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    
    public partial class Films
    {
        public int NumberFilm { get; set; }
        public string NameFilm { get; set; }
        public string OpisanieFilm { get; set; }
        public string DateExitFilm { get; set; }
        public string BudgetFilm { get; set; }
        public string Prodolgitelnost { get; set; }
        public string Genre { get; set; }
        public Nullable<int> NumberCountry { get; set; }

    }
}
