//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uchastie
    {
        public int NumberZapici { get; set; }
        public Nullable<int> NumberHuman { get; set; }
        public Nullable<int> NumberFilm { get; set; }
        public string NumberRole { get; set; }
    }
}
